workflows:
    ios-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          ios_signing:
            distribution_type: ad_hoc
            bundle_identifier: com.example.id